language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

sudo: required
addons:
  chrome: stable
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

#before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#
script:
  - npm --version
  - npm check --integrity
  - npm install
  - npm build
  - npm lint
  - npm test
  - npm test:coverage
  - npm test:a11y
after_success:
  - npm test:codacy-upload
  - npm test:codecov-upload
