version: '2.1'

services:
  dm-show-web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/evidence/dm-show-web:latest
    environment:
    - NODE_ENV=development
    - PORT=8080
    - IDAM_CONTINUE_URL=http://localhost:3608
    - IDAM_API_URL=http://idam-api:8080
    - IDAM_LOGIN_URL=https://localhost:3501/login
    - DM_GW_BASE_URL=http://localhost:3603
    - DM_UPLOAD_URL=http://localhost:3603/documents
    - DM_OWNED_URL=http://localhost:3603/documents/owned
    - DM_SEARCH_URL=http://localhost:3603/documents/filter
    - DM_VIEWER_URL=http://localhost:3621
#      logging env vars
    - ROOT_APPENDER=JSON_CONSOLE
    - LOG_OUTPUT=single
    - JSON_CONSOLE_PRETTY_PRINT=false
    - REFORM_SERVICE_TYPE=node
    - REFORM_SERVICE_NAME=document-management-node-demo
    - REFORM_TEAM=evidence
    - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
    - PACKAGES_ENVIRONMENT=docker
    - PACKAGES_PROJECT=evidence
    - PACKAGES_NAME=document-management-node-demo
    - PACKAGES_VERSION=unkown
    ports:
      - 3608:8080
