version: '3.4'

services:
  webshow:
    build:
        context: .
        target: development
        dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./:/app 
    ports:
      - 3000:3000
  webshow-proxy:
    build:
        context: .
        dockerfile: api/Dockerfile
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3001:3001

  service-auth-provider-app:
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest
    environment:
      - jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      #      - Add key for any microservice that will be used: template-management
      - microserviceKeys_em_gw=AAAAAAAAAAAAAAAA
      - microserviceKeys_dg_docassembly_api=AAAAAAAAAAAAAAAA
      - microserviceKeys_dg_template_management_api=AAAAAAAAAAAAAAAA
      #      logging env vars
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=service-auth-provider-app
      - REFORM_TEAM=rpe
      - REFORM_ENVIRONMENT=docker
      #      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=rpe
      - PACKAGES_NAME=service-auth-provider-app
      - PACKAGES_VERSION=unkown
      - TESTING_SUPPORT_ENABLED=true
    ports:
      - 4502:8489

  em-annotation-app:
    image: hmcts.azurecr.io/hmcts/em-anno:latest
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://annotation-app-db:5432/em-annotation-app
      - SPRING_DATASOURCE_USERNAME=em-annotation-app
      - SPRING_DATASOURCE_PASSWORD=em-annotation-app
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
      # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=em-annotation-app
      - REFORM_TEAM=em-annotation
      - REFORM_ENVIRONMENT=docker
    links:
      - annotation-app-db
      - idam-api
    depends_on:
      - annotation-app-db
      - idam-api
    ports:
      - 4503:8080

  annotation-app-db:
    image: postgres
    environment:
      - POSTGRES_USER=em-annotation-app
      - POSTGRES_PASSWORD=em-annotation-app
      - POSTGRES_DB=em-annotation-app
    ports:
      - 5433:5432

  idam-authentication-web:
    image: hmcts.azurecr.io/hmcts/tidam-authentication-web:latest
    environment:
      IDAM_API_URL: http://idam-api:8080
      IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS: "false"
      REFORM_SERVICE_NAME: idam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
    ports:
      - 3501:8000
    links:
      - idam-api
    depends_on:
      - idam-api

  idam-api:
    image: hmcts.azurecr.io/hmcts/tidam-api:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      IDAM_SUPERUSER_EMAIL: ccd@hmcts.net
      SPRING_DATASOURCE_URL: jdbc:postgresql://idam-database:5432/idam
      SPRING_DATASOURCE_USERNAME: idam-username
      SPRING_DATASOURCE_PASSWORD: idam-password
      SPRING_MAIL_HOST: smtp-server
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      NOTIFY_API_KEY: AAAAAAAAAAAAAAAA
      NOTIFY_CMC_ACTIVATE_USER_TEMPLATE: 76aa8695-64e8-4afd-ae13-bc8385302b1f
      IDAM_SECRET: idam_test_secret
      LOGGING_LEVEL_UK_GOV_HMCTS_IDAM: DEBUG
      IDAM_AUTHENTICATION_WEB_HOST: https://idam-authentication-web:8000
      IDAM_REGISTRATION_WEB_HOST: https://idam-registration-web:8000
      IDAM_WEBSHOW_URL: http://localhost:3000/
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_WEBSHOW: AAAAAAAAAAAAAAAA
      IDAM_CCD_WHITELIST: http://localhost:3451/oauth2redirect
      IDAM_CCD_ADMIN_WHITELIST: https://localhost:3100/oauth2redirect
      IDAM_WEBSHOW_WHITELIST: http://localhost:3000/oauth2/callback
      NOTIFY: "false"
      NOTIFY_CMC_WELCOME_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE: fake
      NOTIFY_SSCS_WELCOME_USER_TEMPLATE: fake
      NOTIFY_WEBSHOW_WELCOME_USER_TEMPLATE: fake
      NOTIFY_RESET_PASSWORD_TEMPLATE: fake
      NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_CCD_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_WEBSHOW_ACTIVATE_USER_TEMPLATE: fake
      REFORM_SERVICE_NAME: idam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
      http_proxy:
      https_proxy:
      no_proxy:
    ports:
      - 4501:8080
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server

  smtp-server:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  idam-database:
    image: postgres
    environment:
      - POSTGRES_USER=idam-username
      - POSTGRES_PASSWORD=idam-password
      - POSTGRES_DB=idam
    ports:
      - 5434:5432

  rpa-dg-docassembly-api:
    image: hmcts.azurecr.io/hmcts/dg-docassembly-api:latest
    environment:
      - S2S_BASE_URI=http://service-auth-provider-app:8489
      - IDAM_API_URL=http://idam-api:8080
      - IDAM_API_BASE_URI=http://idam-api:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test-key
      - DG_TEMPLATE_MANAGEMENT_API=http://rpa-dg-template-management-api:8080
      - DM_STORE_APP_URL=http://dm-store:8080
      - DOCMOSIS_ACCESS_KEY
    links:
      - rpa-dg-template-management-api
      - service-auth-provider-app
    depends_on:
      - rpa-dg-template-management-api
      - service-auth-provider-app
    ports:
      - 4631:8080

  rpa-dg-template-management-api:
    image: hmcts.azurecr.io/hmcts/dg-tmpl-mgmt:latest
    environment:
      - S2S_BASE_URI=http://service-auth-provider-app:8489
      - IDAM_API_URL=http://idam-api:8080
      - IDAM_API_BASE_URI=http://idam-api:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test-key
      - DOCMOSIS_ACCESS_KEY
    links:
      - service-auth-provider-app
    depends_on:
      - service-auth-provider-app
    ports:
      - 4630:8080

  dm-store:
    image: hmcts.azurecr.io/hmcts/dm-store:latest
    command: --wait-for-database 30
    environment:
      - SERVER_PORT=8080
      - IDAM_SUPERUSER_EMAIL
      - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAA
      - GOV_NOTIFY_API_KEY
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dm-store-db:5432/evidence
      - SPRING_DATASOURCE_USERNAME=evidence
      - SPRING_DATASOURCE_PASSWORD=evidence
      - SPRING_PROFILES_ACTIVE=dev
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8489
      - S2S_NAMES_WHITELIST=em_npa_app,sscs,divorce,ccd,em_gw,ccd_gw,em_stitching_api,em_ccd_orchestrator,dg_docassembly_api
      - http_proxy=
      - https_proxy=
      - no_proxy=
      #      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=dm-store
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
      #      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=dm-store
      - PACKAGES_VERSION=unkown
      #      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
      - dm-store-db
      - service-auth-provider-app
    depends_on:
      - dm-store-db
      - service-auth-provider-app
    ports:
      - 4603:8080

  dm-store-db:
    image: postgres
    environment:
      - POSTGRES_USER=evidence
      - POSTGRES_PASSWORD=evidence
      - POSTGRES_DB=evidence
    ports:
      - 5435:5432
