version: '2.1'

services:
  dm-show-web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/evidence/dm-show-web:latest
    environment:
    - NODE_ENV=development
    - PORT=8080
#    ports:
#      - 3608:8080
