test_env: NODE_ENV
login_url: IDAM_LOGIN_URL
dm_gw_url: http://localhost:3603
dm_upload_url: DM_UPLOAD_URL
dm_find_documents_by_creator_url: DM_OWNED_URL
dm_find_documents_by_metadata_url: DM_SEARCH_URL
em_viewer_url: DM_VIEWER_URL
