test_env: NODE_ENV
login_url: IDAM_LOGIN_URL
dm_gw_url: http://localhost:3603
dm_upload_url: DM_UPLOAD_URL
dm_find_documents_by_creator_url: DM_OWNED_URL
dm_find_documents_by_metadata_url: DM_SEARCH_URL
em_viewer_url: DM_VIEWER_URL
dm_url: http://localhost:4603
an_url: http://localhost:4621
idam:
  base_url: IDAM_BASE_URL
  s2s_url: IDAM_S2S_URL
  service_key: IDAM_SERVICE_KEY
  service_name: IDAM_SERVICE_NAME
logging:
  microservice: REFORM_SERVICE_NAME
  team: REFORM_TEAM
  environment: REFORM_ENVIRONMENT
