# Required by Angular
ng_config:
  login_url: https://localhost:3501/login
  dm_store_app_local_endpoint: /demproxy/dm/
  em_anno_app_local_endpoint: /demproxy/an/
  em_redact_app_local_endpoint: /demproxy/re/
  dm_upload_url: /demproxy/dm/documents
  dm_find_documents_by_creator_url: /demproxy/dm/documents/owned/
  dm_find_documents_by_metadata_url: /demproxy/dm/documents/filter/

dm_store_app_url: http://localhost:4603
em_anno_app_url: http://localhost:4621
em_redact_app_url: http://localhost:4621

idam:
  base_url: http://localhost:4501
  s2s_url: http://localhost:4502
  service_key: AAAAAAAAAAAAAAAA
  service_name: em_gw
  login_url: https://localhost:3501/login
  registration_url: https://localhost:3502/register
  client_id: webshow
  client_secret: AAAAAAAAAAAAAAAA

logging:
  microservice: dm-show
  team: evidence
  environment: local

